# Generated by Django 3.1.4 on 2021-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نويسنده', 'verbose_name_plural': 'نويسندگان'},
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, to='api.Book', verbose_name='كتاب\u200cها'),
        ),
    ]
