# Generated by Django 3.1.4 on 2021-03-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210302_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, to='api.Book', verbose_name='كتاب\u200cها'),
        ),
    ]
